# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  backend:
    docker:
      - image: circleci/elixir:1.5
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: parklot_rsvp_test
          POSTGRES_PASSWORD: postgres
    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install Hex locally
          command: mix local.hex --force
          working_directory: ~/app/

      - run:
          name: fetch a copy of rebar
          command: mix local.rebar --force
          working_directory: ~/app/

      - restore_cache:  # restores saved mix cache
          keys:  # list of cache keys, in decreasing specificity
            - v1-mix-cache-{{ checksum "backend/mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run:
          name: get updated dependencies and compile them
          command: mix do deps.get, compile
          working_directory: ~/app/
      - save_cache:  # generate and store cache so `restore_cache` works
          key: v1-mix-cache-{{ checksum "backend/mix.lock" }}
          paths: deps
      - save_cache:  # make another less specific cache
          key: v1-mix-cache-{{ .Branch }}
          paths: deps
      - save_cache:  # you should really save one more cache just in case
          key: v1-mix-cache
          paths: deps
      - save_cache: # don't forget to save a *build* cache, too
          key: v1-mix-cache-{{ checksum "backend/mix.lock" }}
          paths: _build
      - save_cache: # don't forget to save a *build* cache, too
          key: v1-build-cache-{{ .Branch }}
          paths: _build
      - save_cache: # and one more build cache for good measure
          key: v1-build-cache
          paths: _build

      - run: # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: run all tests in project
          command: mix test
          working_directory: ~/app/

      - store_test_results:  # upload test results for display in Test Summary
          path: _build/test/junit

workflows:
  version: 2
  build_and_test:
    jobs:
      - backend

